// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs15rQLdu0jNqgh8KirPWz4j-n6M2IJ5Y',
    appId: '1:631020266512:web:f5971bec961970d95c9695',
    messagingSenderId: '631020266512',
    projectId: 'brgypilasmart',
    authDomain: 'brgypilasmart.firebaseapp.com',
    storageBucket: 'brgypilasmart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGGI_RmMX9nvV77_OS_qNGS41iQ8-CIM',
    appId: '1:631020266512:android:b615e644d5e65d785c9695',
    messagingSenderId: '631020266512',
    projectId: 'brgypilasmart',
    storageBucket: 'brgypilasmart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsXDOJlOkKnrK-i3vlZsk8Iz3YkuYC7TI',
    appId: '1:631020266512:ios:827a97cec82b76125c9695',
    messagingSenderId: '631020266512',
    projectId: 'brgypilasmart',
    storageBucket: 'brgypilasmart.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsXDOJlOkKnrK-i3vlZsk8Iz3YkuYC7TI',
    appId: '1:631020266512:ios:827a97cec82b76125c9695',
    messagingSenderId: '631020266512',
    projectId: 'brgypilasmart',
    storageBucket: 'brgypilasmart.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs15rQLdu0jNqgh8KirPWz4j-n6M2IJ5Y',
    appId: '1:631020266512:web:46a9a760e82f5c695c9695',
    messagingSenderId: '631020266512',
    projectId: 'brgypilasmart',
    authDomain: 'brgypilasmart.firebaseapp.com',
    storageBucket: 'brgypilasmart.firebasestorage.app',
  );
}
